### ISSUE TITLE
Hardware bug

### ISSUE THREAD

**Issue by Wheels39** [hpaluch/temp_meter_16f630#1]
There is a resistor missing between the collector of Q3 and the base of Q2.  4k7 works fine.

**Comment by hpaluch** [comment]
Hi!
It is actually intentional - something called: https://en.wikipedia.org/wiki/Sziklai_pair
In my case it works even without that resistor as can be seen on image:

![PIC16F630 temp meter](https://raw.githubusercontent.com/hpaluch/temp_meter_16f630/master/temp-meter-prototype.jpg)

Could try it without that resistor if it still works for you?

**Comment by Wheels39** [comment]
Hi,I'd forgotten I'd made that comment, it's so long ago!  Monitor the supply current, you will see the problem. The driving transistor isn't being allowed to saturate for want of a collector load.  Good little project though, works fine for me too.  Regards-- Sent from my Android phone with GMX Mail. Please excuse my brevity.On 22/12/2022, 09:33 Henryk Paluch ***@***.***> wrote:

   
  Hi! It is actually intentional - something called: https://en.wikipedia.org/wiki/Sziklai_pair In my case it works even without that resistor as can be seen on image: 
   
  Could try it without that resistor if it still works for you?

**Comment by hpaluch** [comment]
Hi!
Thank you for your effort! It woke up my curiosity - I plan to rebuild this circuit to see what is going there. Please stay tuned.

**Comment by hpaluch** [comment]
Hi, @Wheels39 !

Confirmed (with my nose touching Q1, Q2, and Q3 respectively - Q3 was hot) and fixed adding resistor as you proposed in 4be9fff 

Thank you for contribution!
